### ISSUE TITLE
Allow for non-mesos gitlab instances

### ISSUE THREAD

**Issue by gorlins** [tobilg/gitlab-ci-runner-marathon#2]
Can `GITLAB_SERVICE_NAME` be used directly as the gitlab server url in `CI_SERVER_URL` if it starts with http, or some other way of providing the url indicating an installation outside of the mesos cluster?  I'm new to Mesos but this seems to be an arbitrary limitation - it seems like this runner should be able to work completely independently of the gitlab service itself.

**Comment by tobilg** [comment]
What you mean is that you run a GitLab instance outside of a Mesos / DC/OS cluster, and want to run the GitLab Runners *on* a cluster?

**Comment by gorlins** [comment]
yes.  a simple example is using gitlab.com for hosting git but not paying
for test runners.  If I understand your code correctly, it should work if
it can get the correct url, no?
