### ISSUE TITLE
Upgrade for Gitlab 10?

### ISSUE THREAD

**Issue by kopax** [tobilg/gitlab-ci-runner-marathon#4]
Hi @tobilg , is it possible to have an upgrade for gitlab 10?

**Comment by tobilg** [comment]
There's `tobilg/gitlab-ci-runner-marathon:v10.0.2` available now due to #5

**Comment by kopax** [comment]
It has not being deployed on docker hub.

https://hub.docker.com/r/mesosphere/dcos-gitlab-runner-service/tags/

Is it the same image as the one in `mesosphere/marathon` ?

**Comment by tobilg** [comment]
The mesosphere one was originally forked from this repo. I merged all the changes back to this one and updated it to 10.0.2. 

Not sure why you opened an issue with my repo if you wanted an update of the other one. 

Also, it has nothing to do with Marathon itself

**Comment by tobilg** [comment]
The image is available on the Docker Hub as stated in the first comment.

**Comment by kopax** [comment]
It's all good thank you I miswrote the image name. Thanks for helping!
