### ISSUE TITLE
How to set multiple host with DOCKER_EXTRA_HOSTS

### ISSUE THREAD

**Issue by kopax** [tobilg/gitlab-ci-runner-marathon#6]
I am using `$DOCKER_EXTRA_HOSTS` and I need to set multiple hosts.

I have tried `DOCKER_EXTRA_HOSTS=private:172.16.50.52,npm.example.com:172.16.50.53`

```bash
ERROR: Preparation failed: Error response from daemon: invalid IP address in add-host: "172.16.50.52,npm.example.com:172.16.50.53"
```

I have tried `DOCKER_EXTRA_HOSTS=private:172.16.50.52 --add-host npm.example.com:172.16.50.53`

```bash
ERROR: Preparation failed: Error response from daemon: invalid IP address in add-host: "172.16.50.52 --add-host npm.example.com:172.16.50.53"
```

What is the recommended way to set multiple hosts?

**Comment by tobilg** [comment]
Not sure where you have tried to add this. The entrypoint script https://github.com/tobilg/gitlab-ci-runner-marathon/blob/master/register_and_run.sh doesn't support `DOCKER_EXTRA_HOSTS` at the moment.

**Comment by kopax** [comment]
We need in total two host to map:

- intranet private GitLab
- intranet private Nginx proxy

`DOCKER_EXTRA_HOSTS` is supported and this is the reason why runner are having differents error message.

If it's not with https://github.com/tobilg/gitlab-ci-runner-marathon then who's responsible?

**Comment by tobilg** [comment]
It’s supported by the runner itself, yes, but currently not by the entrypoint script of this project. 

My question was related to how you did try to add the flag. You can always open a PR.

**Comment by kopax** [comment]
Thanks for the clarification. We have set the flag in our deployment plan.

Can you please give me the URL of the repo?

**Comment by tobilg** [comment]
You mean as environment variable in the Marathon application JSON? Have you tried setting `DOCKER_EXTRA_HOSTS="private:172.16.50.52,npm.example.com:172.16.50.53"` (with double-quotes)? I guess they must be escaped when using env vars in Marathon app defs...

**Comment by kopax** [comment]
@tobilg yes I do use the application JSON.

How do you suggest to use the double quotes? Like this?

```diff
{
-   "DOCKER_EXTRA_HOSTS": "private:172.16.50.52,npm.example.com:172.16.50.53",
+  "DOCKER_EXTRA_HOSTS": "\"private:172.16.50.52,npm.example.com:172.16.50.53\"",
}
```
Who's ¨*they*¨ and where is the source code?

**Comment by tobilg** [comment]
"They" as in `DOCKER_EXTRA_HOSTS`. Please use the search engine of your choice to find the source code of GitLab CI.
