### ISSUE TITLE
[Upgrade] upgrade to gitlab 11

### ISSUE THREAD

**Issue by kopax** [tobilg/gitlab-ci-runner-marathon#7]
Hi @tobilg , Our `config.toml` is not able anymore to use `extra_hosts = ["ldap:225.45.35.125"]`, could you please upgrade the image for Gitlab 11? Thanks in advance.

**Comment by tobilg** [comment]
Can you please specify what you mean exactly, or link to some docs which contain the changed behaviour?

**Comment by tobilg** [comment]
You should be able to specify the `DOCKER_EXTRA_HOSTS` environment variable if you start the runner:

```
# gitlab-runner register --help | grep "extra"
Runtime platform                                    arch=amd64 os=linux pid=19 revision=3afdaba6 version=11.5.0
   --docker-extra-hosts value                            Add a custom host-to-IP mapping [$DOCKER_EXTRA_HOSTS]
```

**Comment by kopax** [comment]
Sorry, the issue was not related with this. Gitlab was having security change with their API and I missed it. Sorry for this and thanks.
